const members = [
    {
        name: "Adzana Shaliha",
        picture: "/assets/member/adzana_shaliha.jpg",
        generation: 9,
        graduated: false,
    },
    {
        name: "Angelina Christy",
        picture: "/assets/member/angelina_christy.jpg",
        generation: 7,
        graduated: false,
    },
    {
        name: "Azizi Asadel",
        picture: "/assets/member/azizi_asadel.jpg",
        generation: 7,
        graduated: false,
    },
    {
        name: "Cornelia Vanisa",
        picture: "/assets/member/cornelia_vanisa.jpg",
        generation: 7,
        graduated: false,
    },
    {
        name: "Dhea Angelia",
        picture: "/assets/member/dhea_angelia.jpg",
        generation: 7,
        graduated: false,
    },
    {
        name: "Febriola Sinambela",
        picture: "/assets/member/febriola_sinambela.jpg",
        generation: 7,
        graduated: false,
    },
    {
        name: "Feni Fitriyanti",
        picture: "/assets/member/feni_fitriyanti.jpg",
        generation: 3,
        graduated: false,
    },
    {
        name: "Fiony Alveria Tantri",
        picture: "/assets/member/fiony_alveria.jpg",
        generation: 8,
        graduated: false,
    },
    {
        name: "Flora Shafiq",
        picture: "/assets/member/flora_shafiq.jpg",
        generation: 8,
        graduated: false,
    },
    {
        name: "Fransisca Saraswati Puspa Dewi",
        picture: "/assets/member/fransisca_saraswati_puspa_dewi.jpg",
        generation: 3,
        graduated: false,
    },
    {
        name: "Freya Jayawardana",
        picture: "/assets/member/freya_jayawardana.jpg",
        generation: 7,
        graduated: false,
    },
    {
        name: "Gabriela Margareth Warouw",
        picture: "/assets/member/gabriella.jpg",
        generation: 1,
        graduated: true,
    },
    {
        name: "Gita Sekar Andarini",
        picture: "/assets/member/gita_sekar_andarini.jpg",
        generation: 6,
        graduated: false,
    },
    {
        name: "Helisma Putri",
        picture: "/assets/member/helisma_putri.jpg",
        generation: 7,
        graduated: false,
    },
    {
        name: "Indah Cahya",
        picture: "/assets/member/indah_cahya.jpg",
        generation: 9,
        graduated: false,
    },
    {
        name: "Jessica Chandra",
        picture: "/assets/member/jessica_chandra.jpg",
        generation: 7,
        graduated: false,
    },
    {
        name: "Jesslyn Callista",
        picture: "/assets/member/jesslyn_callista.jpg",
        generation: 7,
        graduated: false,
    },
    {
        name: "Jinan Safa Safira",
        picture: "/assets/member/jinan_safa_safira.jpg",
        generation: 4,
        graduated: false,
    },
    {
        name: "Kathrina Irene",
        picture: "/assets/member/kathrina_irene.jpg",
        generation: 9,
        graduated: false,
    },
    {
        name: "Lulu Salsabila",
        picture: "/assets/member/lulu_salsabila.jpg",
        generation: 8,
        graduated: false,
    },
    {
        name: "Marsha Lenathea",
        picture: "/assets/member/marsha_lenathea.jpg",
        generation: 9,
        graduated: false,
    },
    {
        name: "Mutiara Azzahra",
        picture: "/assets/member/mutiara_azzahra.jpg",
        generation: 7,
        graduated: false,
    },
    {
        name: "Reva Fidela",
        picture: "/assets/member/reva_fidela.jpg",
        generation: 8,
        graduated: false,
    },
    {
        name: "Shani Indira Natio",
        picture: "/assets/member/shani_indira_natio.jpg",
        generation: 3,
        graduated: false,
    },
    {
        name: "Shania Gracia",
        picture: "/assets/member/shania_gracia.jpg",
        generation: 3,
        graduated: false,
    },
    {
        name: "Tan Zhi Hui Celine",
        picture: "/assets/member/tan_zhi_hui_celine.jpg",
        generation: 4,
        graduated: true,
    },
    {
        name: "Yessica Tamara",
        picture: "/assets/member/yessica_tamara.jpg",
        generation: 7,
        graduated: false,
    },
]