export const members = [
  {
    name: 'Gabriela Margareth Warouw',
    picture: '/assets/member/gabriella.jpg',
    generation: 1,
    graduated: true,
  },
  {
    name: 'Feni Fitriyanti',
    picture: '/assets/member/feni_fitriyanti.jpg',
    generation: 3,
    graduated: false,
  },
  {
    name: 'Fransisca Saraswati Puspa Dewi',
    picture: '/assets/member/fransisca_saraswati_puspa_dewi.jpg',
    generation: 3,
    graduated: false,
  },
  {
    name: 'Shani Indira Natio',
    picture: '/assets/member/shani_indira_natio.jpg',
    generation: 3,
    graduated: false,
  },
  {
    name: 'Shania Gracia',
    picture: '/assets/member/shania_gracia.jpg',
    generation: 3,
    graduated: false,
  },
  {
    name: 'Jinan Safa Safira',
    picture: '/assets/member/jinan_safa_safira.jpg',
    generation: 4,
    graduated: false,
  },
  {
    name: 'Tan Zhi Hui Celine',
    picture: '/assets/member/tan_zhi_hui_celine.jpg',
    generation: 4,
    graduated: true,
  },
  {
    name: 'Cindy Hapsari Maharani Pujiantoro Putri',
    picture: '/assets/member/cindy_hapsari.webp',
    generation: 4,
    graduated: true,
  },
  {
    name: 'Gita Sekar Andarini',
    picture: '/assets/member/gita_sekar_andarini.jpg',
    generation: 6,
    graduated: false,
  },
  {
    name: 'Angelina Christy',
    picture: '/assets/member/angelina_christy.jpg',
    generation: 7,
    graduated: false,
  },
  {
    name: 'Azizi Asadel',
    picture: '/assets/member/azizi_asadel.jpg',
    generation: 7,
    graduated: false,
  },
  {
    name: 'Dhea Angelia',
    picture: '/assets/member/dhea_angelia.jpg',
    generation: 7,
    graduated: false,
  },
  {
    name: 'Febriola Sinambela',
    picture: '/assets/member/febriola_sinambela.jpg',
    generation: 7,
    graduated: false,
  },
  {
    name: 'Freya Jayawardana',
    picture: '/assets/member/freya_jayawardana.jpg',
    generation: 7,
    graduated: false,
  },
  {
    name: 'Helisma Putri',
    picture: '/assets/member/helisma_putri.jpg',
    generation: 7,
    graduated: false,
  },
  {
    name: 'Jessica Chandra',
    picture: '/assets/member/jessica_chandra.jpg',
    generation: 7,
    graduated: false,
  },
  {
    name: 'Jesslyn Callista',
    picture: '/assets/member/jesslyn_callista.jpg',
    generation: 7,
    graduated: false,
  },
  {
    name: 'Mutiara Azzahra',
    picture: '/assets/member/mutiara_azzahra.jpg',
    generation: 7,
    graduated: false,
  },
  {
    name: 'Yessica Tamara',
    picture: '/assets/member/yessica_tamara.jpg',
    generation: 7,
    graduated: false,
  },
  // =========================== 8th GENERATION ===========================
  {
    name: 'Cornelia Vanisa',
    picture: '/assets/member/cornelia_vanisa.jpg',
    generation: 8,
    graduated: false,
  },
  {
    name: 'Fiony Alveria Tantri',
    picture: '/assets/member/fiony_alveria.jpg',
    generation: 8,
    graduated: false,
  },
  {
    name: 'Flora Shafiq',
    picture: '/assets/member/flora_shafiq.jpg',
    generation: 8,
    graduated: false,
  },
  {
    name: 'Lulu Salsabila',
    picture: '/assets/member/lulu_salsabila.jpg',
    generation: 8,
    graduated: false,
  },
  {
    name: 'Reva Fidela',
    picture: '/assets/member/reva_fidela.jpg',
    generation: 8,
    graduated: false,
  },
  {
    name: 'Amanina Afiqah',
    picture: '/assets/member/amanina_afiqah.webp',
    generation: 8,
    graduated: true,
  },
  {
    name: 'Amirah Fatin',
    picture: '/assets/member/amirah_fatin.webp',
    generation: 8,
    graduated: true,
  },
  {
    name: 'Cindy Nugroho',
    picture: '/assets/member/cindy_nugroho.webp',
    generation: 8,
    graduated: true,
  },
  {
    name: 'Devytha Maharani',
    picture: '/assets/member/devytha_maharani.webp',
    generation: 8,
    graduated: true,
  },
  {
    name: 'Eriena Kartika',
    picture: '/assets/member/eriena_kartika.webp',
    generation: 8,
    graduated: true,
  },
  {
    name: 'Gabriella Stevany',
    picture: '/assets/member/gabriella_stevany.webp',
    generation: 8,
    graduated: true,
  },
  {
    name: 'Keisya Ramadhani',
    picture: '/assets/member/keisya_ramadhani.webp',
    generation: 8,
    graduated: true,
  },
  {
    name: 'Nyimas Ratu Rafa',
    picture: '/assets/member/nyimas_ratu_rafa.webp',
    generation: 8,
    graduated: true,
  },
  {
    name: 'Pamela Krysanthe',
    picture: '/assets/member/pamela_krysanthe.webp',
    generation: 8,
    graduated: true,
  },
  {
    name: 'Reva Adriana',
    picture: '/assets/member/reva_adriana.webp',
    generation: 8,
    graduated: true,
  },
  {
    name: 'Salma Annisa',
    picture: '/assets/member/salma_annisa.webp',
    generation: 8,
    graduated: true,
  },
  {
    name: 'Umega Maulana',
    picture: '/assets/member/umega_maulana.webp',
    generation: 8,
    graduated: true,
  },
  {
    name: 'Zahra Nur',
    picture: '/assets/member/zahra_nur.webp',
    generation: 8,
    graduated: true,
  },
  // =========================== 9th GENERATION ===========================
  {
    name: 'Adzana Shaliha',
    picture: '/assets/member/adzana_shaliha.jpg',
    generation: 9,
    graduated: false,
  },
  {
    name: 'Indah Cahya',
    picture: '/assets/member/indah_cahya.jpg',
    generation: 9,
    graduated: false,
  },
  {
    name: 'Kathrina Irene',
    picture: '/assets/member/kathrina_irene.jpg',
    generation: 9,
    graduated: false,
  },
  {
    name: 'Marsha Lenathea',
    picture: '/assets/member/marsha_lenathea.jpg',
    generation: 9,
    graduated: false,
  },
  {
    name: 'Caithlyn Gwyneth',
    picture: '/assets/member/caithlyn_gwyneth.webp',
    generation: 9,
    graduated: true,
  },
  {
    name: 'Chalista Ellysia',
    picture: '/assets/member/chalista_ellysia.webp',
    generation: 9,
    graduated: true,
  },
  {
    name: 'Christabel Jocelyn',
    picture: '/assets/member/christabel_jocelyn.webp',
    generation: 9,
    graduated: true,
  },
  {
    name: 'Iris Vevina Prasetio',
    picture: '/assets/member/iris_vevina_prasetio.webp',
    generation: 9,
    graduated: true,
  },
  {
    name: 'Nabila Gusmarlia',
    picture: '/assets/member/nabila_gusmarlia.webp',
    generation: 9,
    graduated: true,
  },
  {
    name: 'Olivia Payten',
    picture: '/assets/member/olivia_payten.webp',
    generation: 9,
    graduated: true,
  },
  {
    name: 'Putri Elzahra',
    picture: '/assets/member/putri_elzahra.webp',
    generation: 9,
    graduated: true,
  },
  {
    name: 'Shinta Devi',
    picture: '/assets/member/shinta_devi.webp',
    generation: 9,
    graduated: true,
  },
  {
    name: 'Tiara Sasi',
    picture: '/assets/member/tiara_sasi.webp',
    generation: 9,
    graduated: true,
  },
  // =========================== 10th GENERATION ===========================
  {
    name: 'Alia Giselle',
    picture: '/assets/member/alia_giselle.jpg',
    generation: 10,
    graduated: false,
  },
  {
    name: 'Amanda Sukma',
    picture: '/assets/member/amanda_sukma.jpg',
    generation: 10,
    graduated: false,
  },
  {
    name: 'Aurellia',
    picture: '/assets/member/aurellia.jpg',
    generation: 10,
    graduated: false,
  },
  {
    name: 'Callista Alifia',
    picture: '/assets/member/callista_alifia.jpg',
    generation: 10,
    graduated: false,
  },
  {
    name: 'Gabriela Abigail',
    picture: '/assets/member/gabriela_abigail.jpg',
    generation: 10,
    graduated: false,
  },
  {
    name: 'Indira Seruni',
    picture: '/assets/member/indira_seruni.jpg',
    generation: 10,
    graduated: false,
  },
  {
    name: 'Jesslyn Elly',
    picture: '/assets/member/jesslyn_elly.jpg',
    generation: 10,
    graduated: false,
  },
  {
    name: 'Raisha Syifa',
    picture: '/assets/member/raisha_syifa.jpg',
    generation: 10,
    graduated: false,
  },
  {
    name: 'Abieza Syabira',
    picture: '/assets/member/abieza_syabira.webp',
    generation: 10,
    graduated: true,
  },
  {
    name: 'Danessa Valerie Hertanto',
    picture: '/assets/member/danessa_valerie.webp',
    generation: 10,
    graduated: true,
  },
  {
    name: 'Naura Safinatunnajah',
    picture: '/assets/member/naura_safinatunnajah.webp',
    generation: 10,
    graduated: true,
  },
];
